import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "chat-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} text-sm ${geistMono.variable} antialiased`}>
        <ThemeProvider defaultTheme="dark" attribute="class" enableSystem={true}>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              error: {
                icon: "❌",
              },
              success: {
                icon: "✅",
              },
              style: {
                backgroundColor: "black",
                color: "white",
                border: "1px solid #272727",
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
